### PR TITLE
tkt48 responsive footer

### LINKED ISSUE #48: Responsive Footer
Adjust the footer file to be responsive so that the locations collapse to one across when using a mobile device.

### PR DESCRIPTION
**Pull request by vricci518**
Adjusted common footer file so that locations are responsive and will stack1 across when viewed on a mobile device.
Closes #48

### CODE REVIEW

**Review by margeschrec — APPROVED** [review]
looks good!

**Review by billythakidd04 — COMMENTED** [review]
This looks good but has it been added to any pages yet?

**Comment by vricci518** [comment]
> This looks good but has it been added to any pages yet?

The common footer had already been added, but it was not behaving responsively. That is an issue we are looking to correct throughout the site

**Comment by vricci518** [comment]
Closes ticket #48

**Pull request merged**
